version: "3"

services:
  ros:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
      - ROS_HOSTNAME=ros
    hostname: ros
    volumes:
      - ./home:$HOME
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /etc/sudoers.d:/etc/sudoers.d:ro
    working_dir: $HOME
    tty: true
    ports:
      - "11311:11311"