version: "3"

services:
  ros:
    image: my-ros:foxy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY
      - ROS_HOSTNAME=ros
    hostname: ros
    volumes:
      - ./home:/home/user
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: tmux
    tty: true